[General]
background=/usr/share/wallpapers/Next/contents/images_dark/5120x2880.png
color=#1d99f3
fontSize=10
headingFont=./fonts/Phudu-Bold.ttf
headingFontSize=118
headingColor=#80ffffff
subHeadingFont=./fonts/Geist-Medium.ttf
subHeadingFontSize=30