[General]
background=/home/shaun/Pictures/Wallpapers/d70bfa7ae620307878ad95428b771bcb.gif
color=#1d99f3
fontSize=10
headingFont=./fonts/Phudu-Bold.ttf
headingFontSize=118
headingColor=#80ffffff
subHeadingFont=./fonts/Geist-Medium.ttf
subHeadingFontSize=30