[General]
background=./assets/dunes.jpg
color=#90ffffff
fontSize=10
headingFont=./fonts/Phudu-Bold.ttf
headingFontSize=118
headingColor=#90ffffff
subHeadingFont=./fonts/Geist-Medium.ttf
subHeadingFontSize=30
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=2